name: PreSubmit-Build

on:
  pull_request:

jobs:
  build:
    name: Build OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - uses: sigstore/cosign-installer@main
    - name: Download binaries
      run: ./download.sh

    - name: Verify sha256 checksums
      run: sha256sum -c DIGESTS

    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        archs: x86_64,aarch64

    - uses: distroless/actions/apko-build@main
      with:
        config: apko.yaml
        tag: distroless-k8s:dev
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64
